import { bodyExcretion } from "./body_excretion";
import { bodyParts } from "./body_parts";

export const questionTranslations = {
  // generalSymptoms: {
  //   fever: {
  //     // fever: {
  //     //   en: "Fever",
  //     //   bn: "Fever",
  //     //   as: "Fever",
  //     // },
  //     feverGrade: {
  //       en: "Fever Grade",
  //       bn: "Fever Grade",
  //       as: "Fever Grade",
  //     },
  //     feverTiming: {
  //       en: "Fever Timing",
  //       bn: "Fever Timing",
  //       as: "Fever Timing",
  //     },
  //     feverMeasured: {
  //       en: "Fever Measured",
  //       bn: "Fever Measured",
  //       as: "Fever Measured",
  //     },
  //     feverDuration: {
  //       en: "Fever Duration",
  //       bn: "Fever Duration",
  //       as: "Fever Duration",
  //     },
  //     feverTemperatureMeasure: {
  //       en: "Fever Temperature Measure",
  //       bn: "Fever Temperature Measure",
  //       as: "Fever Temperature Measure",
  //     },
  //   },
  //   cough: {
  //     cough: {
  //       en: "Cough",
  //       bn: "Cough",
  //       as: "Cough",
  //     },
  //     coughType: {
  //       en: "Cough Type",
  //       bn: "Cough Type",
  //       as: "Cough Type",
  //     },
  //     coughDuration: {
  //       en: "Cough Duration",
  //       bn: "Cough Duration",
  //       as: "Cough Duration",
  //     },
  //     coughTiming: {
  //       en: "Cough Timing",
  //       bn: "Cough Timing",
  //       as: "Cough Timing",
  //     },
  //   },
  //   headache: {
  //     headache: {
  //       en: "Headache",
  //       bn: "Headache",
  //       as: "Headache",
  //     },
  //     headacheDuration: {
  //       en: "Headache Duration",
  //       bn: "Headache Duration",
  //       as: "Headache Duration",
  //     },
  //     headacheTiming: {
  //       en: "Headache Timing",
  //       bn: "Headache Timing",
  //       as: "Headache Timing",
  //     },
  //     headacheFrequency: {
  //       en: "Headache Frequency",
  //       bn: "Headache Frequency",
  //       as: "Headache Frequency",
  //     },
  //     headachePosition: {
  //       en: "Headache Position",
  //       bn: "Headache Position",
  //       as: "Headache Position",
  //     },
  //   },
  //   vomiting: {
  //     vomiting: {
  //       en: "Vomiting",
  //       bn: "Vomiting",
  //       as: "Vomiting",
  //     },
  //     vomitingDuration: {
  //       en: "Vomiting Duration",
  //       bn: "Vomiting Duration",
  //       as: "Vomiting Duration",
  //     },
  //     vomitingTiming: {
  //       en: "Vomiting Timing",
  //       bn: "Vomiting Timing",
  //       as: "Vomiting Timing",
  //     },
  //     vomitingColor: {
  //       en: "Vomiting Color",
  //       bn: "Vomiting Color",
  //       as: "Vomiting Color",
  //     },
  //     vomitingContent: {
  //       en: "Vomiting Content",
  //       bn: "Vomiting Content",
  //       as: "Vomiting Content",
  //     },
  //     vomitingOccurance: {
  //       en: "Vomiting Occurrence",
  //       bn: "Vomiting Occurrence",
  //       as: "Vomiting Occurrence",
  //     },
  //   },
  //   "hair-loss": {
  //     hairlossConfirmation: {
  //       en: "Hair Loss Confirmation",
  //       bn: "Hair Loss Confirmation",
  //       as: "Hair Loss Confirmation",
  //     },
  //     hairlossScalploss: {
  //       en: "Hair Loss Scalp Loss",
  //       bn: "Hair Loss Scalp Loss",
  //       as: "Hair Loss Scalp Loss",
  //     },
  //   },
  //   bleeding: {
  //     bleedingVisible: {
  //       en: "Bleeding Visible",
  //       bn: "Bleeding Visible",
  //       as: "Bleeding Visible",
  //     },
  //     bleedingLocation: {
  //       en: "Bleeding Location",
  //       bn: "Bleeding Location",
  //       as: "Bleeding Location",
  //     },
  //     bleedingBloodlossAmount: {
  //       en: "Bleeding Blood Loss Amount",
  //       bn: "Bleeding Blood Loss Amount",
  //       as: "Bleeding Blood Loss Amount",
  //     },
  //     bleedingDifficultyToStop: {
  //       en: "Bleeding Difficulty to Stop",
  //       bn: "Bleeding Difficulty to Stop",
  //       as: "Bleeding Difficulty to Stop",
  //     },
  //     bleedingDuration: {
  //       en: "Bleeding Duration",
  //       bn: "Bleeding Duration",
  //       as: "Bleeding Duration",
  //     },
  //   },
  //   injury: {
  //     injuryDate: {
  //       en: "Injury Date",
  //       bn: "Injury Date",
  //       as: "Injury Date",
  //     },
  //     injuryPain: {
  //       en: "Injury Pain",
  //       bn: "Injury Pain",
  //       as: "Injury Pain",
  //     },
  //     injuryPainIntensity: {
  //       en: "Injury Pain Intensity",
  //       bn: "Injury Pain Intensity",
  //       as: "Injury Pain Intensity",
  //     },
  //     injurySwelling: {
  //       en: "Injury Swelling",
  //       bn: "Injury Swelling",
  //       as: "Injury Swelling",
  //     },
  //     injuryBleeding: {
  //       en: "Injury Bleeding",
  //       bn: "Injury Bleeding",
  //       as: "Injury Bleeding",
  //     },
  //     injuryMobilityIssues: {
  //       en: "Injury Mobility Issues",
  //       bn: "Injury Mobility Issues",
  //       as: "Injury Mobility Issues",
  //     },
  //     injuryImage: {
  //       en: "Injury Image",
  //       bn: "Injury Image",
  //       as: "Injury Image",
  //     },
  //     injuryCause: {
  //       en: "Injury Cause",
  //       bn: "Injury Cause",
  //       as: "Injury Cause",
  //     },
  //   },
  //   burn: {
  //     burnPain: {
  //       en: "Burn Pain",
  //       bn: "Burn Pain",
  //       as: "Burn Pain",
  //     },
  //     burnSwelling: {
  //       en: "Burn Swelling",
  //       bn: "Burn Swelling",
  //       as: "Burn Swelling",
  //     },
  //     burnImage: {
  //       en: "Burn Image",
  //       bn: "Burn Image",
  //       as: "Burn Image",
  //     },
  //   },
  // },
  // bodyExcretion: {
  //   bodyExcretion: {
  //     en: "Body Excretion",
  //     bn: "Body Excretion",
  //     as: "Body Excretion",
  //   },
  //   stool: {
  //     stool: {
  //       en: "Stool",
  //       bn: "Stool",
  //       as: "Stool",
  //     },
  //     "stool-type": {
  //       en: "Stool Type",
  //       bn: "Stool Type",
  //       as: "Stool Type",
  //     },
  //     "stool-odor": {
  //       en: "Stool Odor",
  //       bn: "Stool Odor",
  //       as: "Stool Odor",
  //     },
  //     "stool-frequency": {
  //       en: "Stool Frequency",
  //       bn: "Stool Frequency",
  //       as: "Stool Frequency",
  //     },
  //     "stool-constipation": {
  //       en: "Stool Constipation",
  //       bn: "Stool Constipation",
  //       as: "Stool Constipation",
  //     },
  //     "Stool-blood": {
  //       en: "Stool Blood",
  //       bn: "Stool Blood",
  //       as: "Stool Blood",
  //     },
  //   },

  //   sputum: {
  //     sputum: {
  //       en: "Sputum",
  //       bn: "Sputum",
  //       as: "Sputum",
  //     },
  //     "sputum-color": {
  //       en: "Sputum Colour",
  //       bn: "Sputum Colour",
  //       as: "Sputum Colour",
  //     },
  //     "sputum-blood": {
  //       en: "Sputum Blood",
  //       bn: "Sputum Blood",
  //       as: "Sputum Blood",
  //     },
  //     "sputum-frequency": {
  //       en: "Sputum Frequency",
  //       bn: "Sputum Frequency",
  //       as: "Sputum Frequency",
  //     },
  //   },
  //   sweat: {
  //     sweat: {
  //       en: "Sweat",
  //       bn: "Sweat",
  //       as: "Sweat",
  //     },
  //     "sweat-amount": {
  //       en: "Sweat Amount",
  //       bn: "Sweat Amount",
  //       as: "Sweat Amount",
  //     },
  //     "sweat-location": {
  //       en: "Sweat Location",
  //       bn: "Sweat Location",
  //       as: "Sweat Location",
  //     },
  //     "sweat-odor": {
  //       en: " Sweat Odor",
  //       bn: " Sweat Odor",
  //       as: " Sweat Odor",
  //     },
  //   },
  //   saliva: {
  //     saliva: {
  //       en: "Saliva",
  //       bn: "Saliva",
  //       as: "Saliva",
  //     },
  //     "salaiva-amount": {
  //       en: "Saliva Amount",
  //       bn: "Saliva Amount",
  //       as: "Saliva Amount",
  //     },
  //     "salaiva-taste": {
  //       en: "Saliva Taste",
  //       bn: "Saliva Taste",
  //       as: "Saliva Taste",
  //     },
  //   },
  //   menstural: {
  //     menstural: {
  //       en: "Menstrual",
  //       bn: "Menstrual",
  //       as: "Menstrual",
  //     },
  //     "menstural-status": {
  //       en: "Menstrual Status",
  //       bn: "Menstrual Status",
  //       as: "Menstrual Status",
  //     },
  //     "menstural-amount": {
  //       en: "Menstrual Amount",
  //       bn: "Menstrual Amount",
  //       as: "Menstrual Amount",
  //     },
  //     "menstural-duration": {
  //       en: "Menstrual Duration",
  //       bn: "Menstrual Duration",
  //       as: "Menstrual Duration",
  //     },
  //     "menstural-clots": {
  //       en: "Menstrual Clots",
  //       bn: "Menstrual Clots",
  //       as: "Menstrual Clots",
  //     },
  //   },
  //   urination: {
  //     urination: {
  //       en: "Urination",
  //       bn: "Urination",
  //       as: "Urination",
  //     },
  //     "urine-frequency": {
  //       en: "Urine Frequency	",
  //       bn: "Urine Frequency	",
  //       as: "Urine Frequency	",
  //     },
  //     "urine-color": {
  //       en: "Urine Color	",
  //       bn: "Urine Color	",
  //       as: "Urine Color	",
  //     },
  //     "urine-odor": {
  //       en: "Urine Odor",
  //       bn: "Urine Odor",
  //       as: "Urine Odor",
  //     },
  //     "urine-discomfort": {
  //       en: "Urine Discomfort",
  //       bn: "Urine Discomfort",
  //       as: "Urine Discomfort",
  //     },
  //     "urine-control": {
  //       en: "Urine Control",
  //       bn: "Urine Control",
  //       as: "Urine Control",
  //     },
  //   },
  // },

  generalSymptoms: {
    fever: {
      feverGrade: {
        en: "Fever Grade",
        bn: "জ্বরের মাত্রা",
        as: "জ্বৰৰ মাত্ৰা",
      },
      feverTiming: {
        en: "Fever Timing",
        bn: "জ্বরের সময়",
        as: "জ্বৰৰ সময়",
      },
      feverMeasured: {
        en: "Fever Measured",
        bn: "জ্বর পরিমাপ",
        as: "জ্বৰ জোখা হৈছে",
      },
      feverDuration: {
        en: "Fever Duration",
        bn: "জ্বরের সময়কাল",
        as: "জ্বৰৰ সময়সীমা",
      },
      feverTemperatureMeasure: {
        en: "Fever Temperature Measure",
        bn: "জ্বরের তাপমাত্রা পরিমাপ",
        as: "জ্বৰৰ উষ্ণতাৰ জোখ",
      },
    },
    cough: {
      cough: {
        en: "Cough",
        bn: "কাশি",
        as: "কাহ",
      },
      coughType: {
        en: "Cough Type",
        bn: "কাশির ধরণ",
        as: "কাহৰ প্ৰকাৰ",
      },
      coughDuration: {
        en: "Cough Duration",
        bn: "কাশির সময়কাল",
        as: "কাহৰ সময়সীমা",
      },
      coughTiming: {
        en: "Cough Timing",
        bn: "কাশির সময়",
        as: "কাহৰ সময়",
      },
    },
    headache: {
      headache: {
        en: "Headache",
        bn: "মাথাব্যথা",
        as: "মূৰৰ বিষ",
      },
      headacheDuration: {
        en: "Headache Duration",
        bn: "মাথাব্যথার সময়কাল",
        as: "মূৰৰ বিষৰ সময়সীমা",
      },
      headacheTiming: {
        en: "Headache Timing",
        bn: "মাথাব্যথার সময়",
        as: "মূৰৰ বিষৰ সময়",
      },
      headacheFrequency: {
        en: "Headache Frequency",
        bn: "মাথাব্যথার ফ্রিকোয়েন্সি",
        as: "মূৰৰ বিষৰ সঘনতা",
      },
      headachePosition: {
        en: "Headache Position",
        bn: "মাথাব্যথার অবস্থান",
        as: "মূৰৰ বিষৰ অৱস্থান",
      },
    },
    vomiting: {
      vomiting: {
        en: "Vomiting",
        bn: "বমি",
        as: "বমি",
      },
      vomitingDuration: {
        en: "Vomiting Duration",
        bn: "বমির সময়কাল",
        as: "বমিৰ সময়সীমা",
      },
      vomitingTiming: {
        en: "Vomiting Timing",
        bn: "বমির সময়",
        as: "বমিৰ সময়",
      },
      vomitingColor: {
        en: "Vomiting Color",
        bn: "বমির রঙ",
        as: "বমিৰ ৰং",
      },
      vomitingContent: {
        en: "Vomiting Content",
        bn: "বমির বিষয়বস্তু",
        as: "বমিৰ সামগ্ৰী",
      },
      vomitingOccurance: {
        en: "Vomiting Occurrence",
        bn: "বমির ঘটনা",
        as: "বমিৰ সংঘটন",
      },
    },
    "hair-loss": {
      hairlossConfirmation: {
        en: "Hair Loss Confirmation",
        bn: "চুল পড়া নিশ্চিতকরণ",
        as: "চুলি সৰাৰ নিশ্চিতকৰণ",
      },
      hairlossScalploss: {
        en: "Hair Loss Scalp Loss",
        bn: "চুল পড়া মাথার ত্বক হারানো",
        as: "চুলি সৰা মূৰৰ ছালৰ সৰা",
      },
    },
    bleeding: {
      // bleedingVisible: {
      //   en: "Bleeding Visible",
      //   bn: "রক্তপাত দৃশ্যমান",
      //   as: "ৰক্তক্ষৰণ দৃশ্যমান",
      // },
      bleedingLocation: {
        en: "Bleeding Location",
        bn: "রক্তপাতের অবস্থান",
        as: "ৰক্তক্ষৰণৰ স্থান",
      },
      bleedingBloodlossAmount: {
        en: "Bleeding Blood Loss Amount",
        bn: "রক্তপাতের পরিমাণ",
        as: "ৰক্তক্ষৰণৰ পৰিমাণ",
      },
      bleedingDifficultyToStop: {
        en: "Bleeding Difficulty to Stop",
        bn: "রক্তপাত বন্ধ করতে অসুবিধা",
        as: "ৰক্তক্ষৰণ বন্ধ কৰাত অসুবিধা",
      },
      bleedingDuration: {
        en: "Bleeding Duration",
        bn: "রক্তপাতের সময়কাল",
        as: "ৰক্তক্ষৰণৰ সময়সীমা",
      },
    },
    injury: {
      injuryDate: {
        en: "Injury Date",
        bn: "আঘাতের তারিখ",
        as: "আঘাতৰ তাৰিখ",
      },
      injuryPain: {
        en: "Injury Pain",
        bn: "আঘাতের ব্যথা",
        as: "আঘাতৰ বিষ",
      },
      injuryPainIntensity: {
        en: "Injury Pain Intensity",
        bn: "আঘাতের ব্যথার তীব্রতা",
        as: "আঘাতৰ বিষৰ প্ৰাবল্য",
      },
      injurySwelling: {
        en: "Injury Swelling",
        bn: "আঘাতের ফোলা",
        as: "আঘাতৰ ফুলা",
      },
      injuryBleeding: {
        en: "Injury Bleeding",
        bn: "আঘাতের রক্তপাত",
        as: "আঘাতৰ ৰক্তক্ষৰণ",
      },
      injuryMobilityIssues: {
        en: "Injury Mobility Issues",
        bn: "আঘাতের গতিশীলতার সমস্যা",
        as: "আঘাতৰ গতিশীলতাৰ সমস্যা",
      },
      injuryImage: {
        en: "Injury Image",
        bn: "আঘাতের ছবি",
        as: "আঘাতৰ ছবি",
      },
      injuryCause: {
        en: "Injury Cause",
        bn: "আঘাতের কারণ",
        as: "আঘাতৰ কাৰণ",
      },
    },
    burn: {
      burnPain: {
        en: "Burn Pain",
        bn: "পোড়ার ব্যথা",
        as: "পোৰাৰ বিষ",
      },
      burnSwelling: {
        en: "Burn Swelling",
        bn: "পোড়ার ফোলা",
        as: "পোৰাৰ ফুলা",
      },
      burnImage: {
        en: "Burn Image",
        bn: "পোড়ার ছবি",
        as: "পোৰাৰ ছবি",
      },
    },
  },
  bodyExcretion: {
    bodyExcretion: {
      en: "Body Excretion",
      bn: "শরীর থেকে বর্জ্য ত্যাগ",
      as: "শৰীৰৰ মলত্যাগ",
    },
    stool: {
      stool: {
        en: "Stool",
        bn: "মল",
        as: "মল",
      },
      "stool-type": {
        en: "Stool Type",
        bn: "মলের ধরণ",
        as: "মলৰ প্ৰকাৰ",
      },
      "stool-odor": {
        en: "Stool Odor",
        bn: "মলের গন্ধ",
        as: "মলৰ গোন্ধ",
      },
      "stool-frequency": {
        en: "Stool Frequency",
        bn: "মলের ফ্রিকোয়েন্সি",
        as: "মলৰ সঘনতা",
      },
      "stool-constipation": {
        en: "Stool Constipation",
        bn: "মলের কোষ্ঠকাঠিন্য",
        as: "মলৰ কোষ্ঠকাঠিন্য",
      },
      "Stool-blood": {
        en: "Stool Blood",
        bn: "মলে রক্ত",
        as: "মলত তেজ",
      },
    },
    sputum: {
      sputum: {
        en: "Sputum",
        bn: "কফ",
        as: "খেকাৰ",
      },
      "sputum-color": {
        en: "Sputum Colour",
        bn: "কফের রঙ",
        as: "খেকাৰৰ ৰং",
      },
      "sputum-blood": {
        en: "Sputum Blood",
        bn: "কফে রক্ত",
        as: "খেকাৰত তেজ",
      },
      "sputum-frequency": {
        en: "Sputum Frequency",
        bn: "কফের ফ্রিকোয়েন্সি",
        as: "খেকাৰৰ সঘনতা",
      },
    },
    sweat: {
      sweat: {
        en: "Sweat",
        bn: "ঘাম",
        as: "ঘাম",
      },
      "sweat-amount": {
        en: "Sweat Amount",
        bn: "ঘামের পরিমাণ",
        as: "ঘামৰ পৰিমাণ",
      },
      "sweat-location": {
        en: "Sweat Location",
        bn: "ঘামের অবস্থান",
        as: "ঘামৰ অৱস্থান",
      },
      "sweat-odor": {
        en: " Sweat Odor",
        bn: "ঘামের গন্ধ",
        as: "ঘামৰ গোন্ধ",
      },
    },
    saliva: {
      saliva: {
        en: "Saliva",
        bn: "লালা",
        as: "লালা",
      },
      "saliva-amount": {
        en: "Saliva Amount",
        bn: "লালার পরিমাণ",
        as: "লালাৰ পৰিমাণ",
      },
      "saliva-taste": {
        en: "Saliva Taste",
        bn: "লালার স্বাদ",
        as: "লালাৰ সোৱাদ",
      },
    },
    menstrual: {
      menstrual: {
        en: "Menstrual",
        bn: "মাসিক",
        as: "মাসিক",
      },
      "menstrual-status": {
        en: "Menstrual Status",
        bn: "মাসিকের অবস্থা",
        as: "মাসিকৰ অৱস্থা",
      },
      "menstrual-amount": {
        en: "Menstrual Amount",
        bn: "মাসিকের পরিমাণ",
        as: "মাসিকৰ পৰিমাণ",
      },
      "menstrual-duration": {
        en: "Menstrual Duration",
        bn: "মাসিকের সময়কাল",
        as: "মাসিকৰ সময়সীমা",
      },
      "menstrual-clots": {
        en: "Menstrual Clots",
        bn: "মাসিকের জমাট",
        as: "মাসিকৰ তেজ গোট মৰা",
      },
    },
    urination: {
      urination: {
        en: "Urination",
        bn: "প্রস্রাব",
        as: "প্ৰস্ৰাৱ",
      },
      "urine-frequency": {
        en: "Urine Frequency ",
        bn: "প্রস্রাবের ফ্রিকোয়েন্সি",
        as: "প্ৰস্ৰাৱৰ সঘনতা",
      },
      "urine-color": {
        en: "Urine Color ",
        bn: "প্রস্রাবের রঙ",
        as: "প্ৰস্ৰাৱৰ ৰং",
      },
      "urine-odor": {
        en: "Urine Odor",
        bn: "প্রস্রাবের গন্ধ",
        as: "প্ৰস্ৰাৱৰ গোন্ধ",
      },
      "urine-discomfort": {
        en: "Urine Discomfort",
        bn: "প্রস্রাবের অস্বস্তি",
        as: "প্ৰস্ৰাৱত অসুবিধা",
      },
      "urine-control": {
        en: "Urine Control",
        bn: "প্রস্রাব নিয়ন্ত্রণ",
        as: "প্ৰস্ৰাৱ নিয়ন্ত্ৰণ",
      },
    },
  },
  skin: {
    "my-skin": {
      mySkinType: {
        en: "Skin Type",
        bn: "ত্বকের ধরন",
        as: "ছালৰ প্ৰকাৰ",
      },
      mySkinColor: {
        en: "Skin Color",
        bn: "ত্বকের রং",
        as: "ছালৰ ৰং",
      },
      mySkinSurface: {
        en: "Skin Surface Conditions",
        bn: "ত্বকের উপরিভাগের সমস্যা",
        as: "ছালৰ উপৰিভাগৰ সমস্যা",
      },
      skinIssuesConfirmation: {
        en: "Skin Issues",
        bn: "ত্বকের সমস্যা",
        as: "ছালৰ সমস্যা",
      },
      skinIssuesTypePain: {
        en: "Pain",
        bn: "ব্যথা",
        as: "বিষ",
      },
      skinIssuePainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ প্ৰাবল্য",
      },
      skinIssuePainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরন",
        as: "বিষৰ প্ৰকাৰ",
      },
      skinIssuePainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়",
        as: "বিষৰ সময়",
      },
      skinIssuesTypeItching: {
        en: "Itching",
        bn: "চুলকানি",
        as: "খুজলি",
      },
      skinIchitingOnset: {
        en: "Itching Onset",
        bn: "চুলকানি শুরুর সময়",
        as: "খুজলি আৰম্ভ হোৱাৰ সময়",
      },
      skinIchitingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "খুজলিৰ সময়সীমা",
      },
      skinIchitingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "খুজলিৰ ছবি",
      },
      skinIssuesTypeSwelling: {
        en: "Swelling",
        bn: "ফোলা",
        as: "ফুলা",
      },
      skinIssueSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলা চকুত পৰে নেকি",
      },
      skinIssueSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      skinIssuesTypeRash: {
        en: "Rash/Bruising",
        bn: "ফুসকুড়ি/কালশিরা",
        as: "ফোহা/ৰঙচুৱা দাগ",
      },
      skinIssueRashBruisingVisibility: {
        en: "Rash/Bruising Visibility",
        bn: "র‍্যাশ/দাগের দৃশ্যমানতা",
        as: "ৰেচ/দাগ চকুত পৰে নেকি",
      },
      skinIssueRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "র‍্যাশ/দাগের ছবি",
        as: "ৰেচ/দাগৰ ছবি",
      },
    },
  },
  bodyParts: {
    calf: {
      bodyPartsCalfPain: {
        en: "Calf Pain",
        bn: "পায়ের পেশিতে ব্যথা",
        as: "ভৰিৰ পেশীত বিষ",
      },
      bodyPartsCalfPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsCalfPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsCalfPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsCalfSwelling: {
        en: "Calf Swelling",
        bn: "পায়ের পেশিতে ফোলা",
        as: "ভৰিৰ পেশী ফুলা",
      },
      bodyPartsCalfSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsCalfSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsCalfRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsCalfRashBruisingVisibility: {
        en: "Rash/Bruising Visibility",
        bn: "চুলকানি/রক্তজমাট দৃশ্যমানতা",
        as: "চুলকনি/ৰক্ত জমাৰ দৃশ্যতা",
      },
      bodyPartsCalfRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsCalfItching: {
        en: "Itching in Calf",
        bn: "পায়ের পেশিতে চুলকানি",
        as: "ভৰিৰ পেশীত চুলকনি",
      },
      bodyPartsCalfItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsCalfItchingDuration: {
        en: "Duration of Itching",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsCalfItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsCalfOthers: {
        en: "Other Calf Symptoms",
        bn: "অন্যান্য পায়ের পেশির উপসর্গ",
        as: "অন্যান্য ভৰিৰ পেশীৰ লক্ষণ",
      },
    },
    // eyes: {
    //   bodyPartsEyePain: {},
    //   bodyPartsEyePainIntensity: {},
    //   bodyPartsEyePainPattern: {},
    //   bodyPartsEyePainTiming: {},
    //   bodyPartsEyeSwelling: {},
    //   bodyPartsEyeSwellingVisibility: {},
    //   bodyPartsEyeSwellingImage: {},
    //   bodyPartsEyesRedness: {},
    //   bodyPartsEyesBurning: {},
    //   bodyPartsEyesBlurryVision: {},
    //   bodyPartsEyeItching: {},
    //   bodyPartsEyeItchingSuddenOnset: {},
    //   bodyPartsEyeItchingDuration: {},
    //   bodyPartsEyeItchingImage: {},
    // },
    eyes: {
      bodyPartsEyesPain: {
        en: "Eye Pain",
        bn: "চোখে ব্যথা",
        as: "চকুত বিষ",
      },
      bodyPartsEyesPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsEyesPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsEyesPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsEyesSwelling: {
        en: "Eye Swelling",
        bn: "চোখ ফোলা",
        as: "চকু ফুলা",
      },
      bodyPartsEyesSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsEyesSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsEyesRedness: {
        en: "Eye Redness",
        bn: "চোখ লাল হওয়া",
        as: "চকু ৰঙা হোৱা",
      },
      bodyPartsEyesBurning: {
        en: "Burning Sensation",
        bn: "জ্বালাপোড়া অনুভব",
        as: "জ্বলা অনুভূতি",
      },
      bodyPartsEyesBlurryVision: {
        en: "Blurry Vision",
        bn: "ঝাপসা দৃষ্টি",
        as: "অস্পষ্ট দৃষ্টি",
      },
      bodyPartsEyesItching: {
        en: "Eye Itching",
        bn: "চোখে চুলকানি",
        as: "চকুত চুলকনি",
      },
      bodyPartsEyesItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsEyesItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsEyesItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
    },

    // forehead: {
    //   bodyPartsForeheadPain: {},
    //   bodyPartsForeheadPainIntensity: {},
    //   bodyPartsForeheadPainPattern: {},
    //   bodyPartsForeheadPainTiming: {},
    //   bodyPartsForeheadSwelling: {},
    //   bodyPartsForeheadSwellingVisibility: {},
    //   bodyPartsForeheadSwellingImage: {},
    //   bodyPartsForeheadRash: {},
    //   bodyPartsForeheadRashVisibility: {},
    //   bodyPartsForeheadRashImage: {},
    //   bodyPartsForeheadOthers: {},
    // },
    forehead: {
      bodyPartsForeheadPain: {
        en: "Forehead Pain",
        bn: "কপালে ব্যথা",
        as: "কপালত বিষ",
      },
      bodyPartsForeheadPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsForeheadPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsForeheadPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsForeheadSwelling: {
        en: "Forehead Swelling",
        bn: "কপালে ফোলা",
        as: "কপালত ফুলা",
      },
      bodyPartsForeheadSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsForeheadSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsForeheadRash: {
        en: "Rash on Forehead",
        bn: "কপালে চুলকানি বা ফুসকুড়ি",
        as: "কপালত ৰেশ বা চুলকনি",
      },
      bodyPartsForeheadRashVisibility: {
        en: "Rash Visibility",
        bn: "চুলকানি/ফুসকুড়ির দৃশ্যমানতা",
        as: "ৰেশৰ দৃশ্যতা",
      },
      bodyPartsForeheadRashImage: {
        en: "Rash Image",
        bn: "চুলকানি/ফুসকুড়ির ছবি",
        as: "ৰেশৰ ছবি",
      },
      bodyPartsForeheadOthers: {
        en: "Other Forehead Symptoms",
        bn: "অন্যান্য কপালের উপসর্গ",
        as: "অন্যান্য কপালৰ লক্ষণ",
      },
    },
    // ears: {
    //   bodyPartsEarPain: {},
    //   bodyPartsEarPainIntensity: {},
    //   bodyPartsEarPainPattern: {},
    //   bodyPartsEarPainTiming: {},
    //   bodyPartsEarsHearingLoss: {},
    //   bodyPartsEarsDischarge: {},
    //   bodyPartsEarsDischargeNature: {},
    //   bodyPartsEarsItching: {},
    //   bodyPartsEarsItchingSuddenOnset: {},
    //   bodyPartsEarsItchingDuration: {},
    //   bodyPartsEarsItchingImage: {},
    // },
    ears: {
      bodyPartsEarsPain: {
        en: "Ear Pain",
        bn: "কানে ব্যথা",
        as: "কাণত বিষ",
      },
      bodyPartsEarsPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsEarsPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsEarsPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsEarsHearingLoss: {
        en: "Hearing Loss",
        bn: "শোনার ক্ষমতা হ্রাস",
        as: "শুনাৰ ক্ষমতা হ্ৰাস",
      },
      bodyPartsEarsDischarge: {
        en: "Ear Discharge",
        bn: "কান থেকে তরল নিঃসরণ",
        as: "কাণৰ পৰা নিঃসৰণ",
      },
      bodyPartsEarsDischargeNature: {
        en: "Nature of Discharge",
        bn: "নিঃসরণের ধরন",
        as: "নিঃসৰণৰ প্ৰকৃতি",
      },
      bodyPartsEarsItching: {
        en: "Ear Itching",
        bn: "কানে চুলকানি",
        as: "কাণত চুলকনি",
      },
      bodyPartsEarsItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsEarsItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsEarsItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
    },
    // nose: {
    //   bodyPartsNoseCongestion: {},
    //   bodyPartsNoseRunny: {},
    //   bodyPartsNoseBleed: {},
    //   bodyPartsNoseLossOfSmell: {},
    //   bodyPartsNoseItching: {},
    //   bodyPartsNoseItchingSuddenOnset: {},
    //   bodyPartsNoseItchingDuration: {},
    //   bodyPartsNoseItchingImage: {},
    //   bodyPartsNoseOthers: {},
    // },
    nose: {
      bodyPartsNoseCongestion: {
        en: "Nasal Congestion",
        bn: "নাক বন্ধ থাকা",
        as: "নাক বন্ধ হৈ থকা",
      },
      bodyPartsNoseRunny: {
        en: "Runny Nose",
        bn: "নাক দিয়ে পানি পড়া",
        as: "নাকৰ পৰা পানী ওলোৱা",
      },
      bodyPartsNoseBleed: {
        en: "Nose Bleed",
        bn: "নাক থেকে রক্ত পড়া",
        as: "নাকৰ পৰা ৰক্ত ওলোৱা",
      },
      bodyPartsNoseLossOfSmell: {
        en: "Loss of Smell",
        bn: "ঘ্রাণশক্তি হ্রাস",
        as: "ঘ্ৰাণশক্তি হ্ৰাস",
      },
      bodyPartsNoseItching: {
        en: "Nose Itching",
        bn: "নাকে চুলকানি",
        as: "নাকত চুলকনি",
      },
      bodyPartsNoseItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsNoseItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsNoseItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsNoseOthers: {
        en: "Other Nasal Symptoms",
        bn: "অন্যান্য নাকের উপসর্গ",
        as: "অন্যান্য নাকৰ লক্ষণ",
      },
    },
    // "mouth/Lips": {
    //   bodyPartsMouthLipsPain: {},
    //   bodyPartsMouthLipsPainIntensity: {},
    //   bodyPartsMouthLipsPainPattern: {},
    //   bodyPartsMouthLipsPainTiming: {},
    //   bodyPartsMouthLipsSwelling: {},
    //   bodyPartsMouthLipsSwellingVisibility: {},
    //   bodyPartsMouthLipsSwellingImage: {},
    //   bodyPartsMouthUlcers: {},
    //   bodyPartsMouthBadBreath: {},
    //   bodyPartsMouthLipsOthers: {},
    // },
    "mouth-lips": {
      bodyPartsMouthLipsPain: {
        en: "Mouth/Lips Pain",
        bn: "মুখ বা ঠোঁটে ব্যথা",
        as: "মুখ বা ঠোঁটত বিষ",
      },
      bodyPartsMouthLipsPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsMouthLipsPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsMouthLipsPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsMouthLipsSwelling: {
        en: "Mouth/Lips Swelling",
        bn: "মুখ বা ঠোঁটে ফোলা",
        as: "মুখ বা ঠোঁটত ফুলা",
      },
      bodyPartsMouthLipsSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsMouthLipsSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsMouthUlcers: {
        en: "Mouth Ulcers",
        bn: "মুখে ঘা",
        as: "মুখত ঘা",
      },
      bodyPartsMouthBadBreath: {
        en: "Bad Breath",
        bn: "দুর্গন্ধযুক্ত নিঃশ্বাস",
        as: "বেয়া গন্ধ থকা নিশ্বাস",
      },
      bodyPartsMouthLipsOthers: {
        en: "Other Mouth/Lips Symptoms",
        bn: "অন্যান্য মুখ/ঠোঁটের উপসর্গ",
        as: "অন্যান্য মুখ/ঠোঁটৰ লক্ষণ",
      },
    },
    // neck: {
    //   bodyPartsNeckPain: {},
    //   bodyPartsNeckPainIntensity: {},
    //   bodyPartsNeckPainPattern: {},
    //   bodyPartsNeckPainTiming: {},
    //   bodyPartsNeckSwelling: {},
    //   bodyPartsNeckSwellingVisibility: {},
    //   bodyPartsNeckSwellingImage: {},
    //   bodyPartsNeckStiffness: {},
    //   bodyPartsNeckRashBruising: {},
    //   bodyPartsNeckRashBruisingVisibility: {},
    //   bodyPartsNeckRashBruisingImage: {},
    //   bodyPartsNeckItching: {},
    // },
    neck: {
      bodyPartsNeckPain: {
        en: "Neck Pain",
        bn: "গলায় ব্যথা",
        as: "গলাত বিষ",
      },
      bodyPartsNeckPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsNeckPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsNeckPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsNeckSwelling: {
        en: "Neck Swelling",
        bn: "গলায় ফোলা",
        as: "গলাত ফুলা",
      },
      bodyPartsNeckSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsNeckSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsNeckStiffness: {
        en: "Neck Stiffness",
        bn: "গলা শক্ত হয়ে যাওয়া",
        as: "গলা শক্ত হোৱা",
      },
      bodyPartsNeckRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsNeckRashBruisingVisibility: {
        en: "Rash/Bruising Visibility",
        bn: "চুলকানি/রক্তজমাট দৃশ্যমানতা",
        as: "চুলকনি/ৰক্ত জমাৰ দৃশ্যতা",
      },
      bodyPartsNeckRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsNeckItching: {
        en: "Neck Itching",
        bn: "গলায় চুলকানি",
        as: "গলাত চুলকনি",
      },
      bodyPartsNeckItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsNeckItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsNeckItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsNeckOthers: {
        en: "Other neck Symptoms",
        bn: "অন্যান্য গলার উপসর্গ",
        as: "ডিঙিৰ অন্যান্য লক্ষণ",
      },
    },

    // upperArm: {
    //   bodyPartsUpperArmPain: {},
    //   bodyPartsUpperArmPainWhichArm: {},
    //   bodyPartsUpperArmPainIntensity: {},
    //   bodyPartsUpperArmPainPattern: {},
    //   bodyPartsUpperArmPainTiming: {},
    //   bodyPartsUpperArmSwelling: {},
    //   bodyPartsUpperArmSwellingWhichArm: {},
    //   bodyPartsUpperArmSwellingVisibility: {},
    //   bodyPartsUpperArmSwellingImage: {},
    //   bodyPartsUpperArmStiffness: {},
    //   bodyPartsUpperArmStiffnessWhichArm: {},
    //   bodyPartsUpperArmRashBruising: {},
    //   bodyPartsUpperArmRashBruisingWhichArm: {},
    //   bodyPartsUpperArmRashBruisingImage: {},
    //   bodyPartsUpperArmItching: {},
    //   bodyPartsUpperArmItchingWhichArm: {},
    //   bodyPartsUpperArmItchingSuddenOnset: {},
    //   bodyPartsUpperArmItchingDuration: {},
    //   bodyPartsUpperArmItchingImage: {},
    //   bodyPartsUpperArmOthers: {},
    // },
    upperArm: {
      bodyPartsUpperArmPain: {
        en: "Upper Arm Pain",
        bn: "উপরের বাহুতে ব্যথা",
        as: "ওপৰৰ বাহুত বিষ",
      },
      bodyPartsUpperArmPainWhichArm: {
        en: "Which Arm has Pain?",
        bn: "কোন বাহুতে ব্যথা?",
        as: "কোন বাহুত বিষ আছে?",
      },
      bodyPartsUpperArmPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsUpperArmPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsUpperArmPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsUpperArmSwelling: {
        en: "Upper Arm Swelling",
        bn: "উপরের বাহুতে ফোলা",
        as: "ওপৰৰ বাহুত ফুলা",
      },
      bodyPartsUpperArmSwellingWhichArm: {
        en: "Which Arm has Swelling?",
        bn: "কোন বাহুতে ফোলা?",
        as: "কোন বাহুত ফুলা আছে?",
      },
      bodyPartsUpperArmSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsUpperArmSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsUpperArmStiffness: {
        en: "Upper Arm Stiffness",
        bn: "উপরের বাহু শক্ত হয়ে যাওয়া",
        as: "ওপৰৰ বাহু শক্ত হোৱা",
      },
      bodyPartsUpperArmStiffnessWhichArm: {
        en: "Which Arm has Stiffness?",
        bn: "কোন বাহু শক্ত হয়েছে?",
        as: "কোন বাহু শক্ত হৈছে?",
      },
      bodyPartsUpperArmRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsUpperArmRashBruisingWhichArm: {
        en: "Which Arm has Rash or Bruising?",
        bn: "কোন বাহুতে চুলকানি বা রক্তজমাট?",
        as: "কোন বাহুত চুলকনি বা ৰক্ত জমা আছে?",
      },
      bodyPartsUpperArmRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsUpperArmItching: {
        en: "Itching in Upper Arm",
        bn: "উপরের বাহুতে চুলকানি",
        as: "ওপৰৰ বাহুত চুলকনি",
      },
      bodyPartsUpperArmItchingWhichArm: {
        en: "Which Arm has Itching?",
        bn: "কোন বাহুতে চুলকানি?",
        as: "কোন বাহুত চুলকনি?",
      },
      bodyPartsUpperArmItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsUpperArmItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsUpperArmItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsUpperArmOthers: {
        en: "Other Upper Arm Symptoms",
        bn: "অন্যান্য উপর বাহুর উপসর্গ",
        as: "অন্যান্য ওপৰ বাহুৰ লক্ষণ",
      },
    },

    // elbow: {
    //   bodyPartsElbowPain: {},
    //   bodyPartsElbowPainWhichArm: {},
    //   bodyPartsElbowPainIntensity: {},
    //   bodyPartsElbowPainPattern: {},
    //   bodyPartsElbowPainTiming: {},
    //   bodyPartsElbowSwelling: {},
    //   bodyPartsElbowSwellingWhichArm: {},
    //   bodyPartsElbowSwellingVisibility: {},
    //   bodyPartsElbowSwellingImage: {},
    //   bodyPartsElbowStiffness: {},
    //   bodyPartsElbowStiffnessWhichArm: {},
    //   bodyPartsElbowRashBruising: {},
    //   bodyPartsElbowRashBruisingWhichArm: {},
    //   bodyPartsElbowRashBruisingImage: {},
    //   bodyPartsElbowItching: {},
    //   bodyPartsElbowItchingWhichArm: {},
    //   bodyPartsElbowItchingSuddenOnset: {},
    //   bodyPartsElbowItchingDuration: {},
    //   bodyPartsElbowItchingImage: {},
    //   bodyPartsElbowOthers: {},
    // },
    elbow: {
      bodyPartsElbowPain: {
        en: "Elbow Pain",
        bn: "কনুইয়ে ব্যথা",
        as: "কনইত বিষ",
      },
      bodyPartsElbowPainWhichArm: {
        en: "Which Arm has Pain?",
        bn: "কোন হাতে কনুইয়ের ব্যথা?",
        as: "কোন হাতত কনইৰ বিষ?",
      },
      bodyPartsElbowPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsElbowPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsElbowPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsElbowSwelling: {
        en: "Elbow Swelling",
        bn: "কনুইয়ে ফোলা",
        as: "কনইত ফুলা",
      },
      bodyPartsElbowSwellingWhichArm: {
        en: "Which Arm has Swelling?",
        bn: "কোন কনুইয়ে ফোলা?",
        as: "কোন কনইত ফুলা?",
      },
      bodyPartsElbowSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsElbowSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsElbowStiffness: {
        en: "Elbow Stiffness",
        bn: "কনুইয়ে শক্ত হয়ে যাওয়া",
        as: "কনই শক্ত হোৱা",
      },
      bodyPartsElbowStiffnessWhichArm: {
        en: "Which Arm has Stiffness?",
        bn: "কোন কনুইয়ে শক্ত হয়েছে?",
        as: "কোন কনই শক্ত হৈছে?",
      },
      bodyPartsElbowRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsElbowRashBruisingWhichArm: {
        en: "Which Arm has Rash or Bruising?",
        bn: "কোন কনুইয়ে চুলকানি বা রক্তজমাট?",
        as: "কোন কনইত চুলকনি বা ৰক্ত জমা?",
      },
      bodyPartsElbowRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsElbowItching: {
        en: "Elbow Itching",
        bn: "কনুইয়ে চুলকানি",
        as: "কনইত চুলকনি",
      },
      bodyPartsElbowItchingWhichArm: {
        en: "Which Arm has Itching?",
        bn: "কোন কনুইয়ে চুলকানি?",
        as: "কোন কনইত চুলকনি?",
      },
      bodyPartsElbowItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsElbowItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsElbowItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsElbowOthers: {
        en: "Other Elbow Symptoms",
        bn: "অন্যান্য কনুইয়ের উপসর্গ",
        as: "অন্যান্য কনইৰ লক্ষণ",
      },
    },
    // forearm: {
    //   bodyPartsForearmPain: {},
    //   bodyPartsForearmPainWhichArm: {},
    //   bodyPartsForearmPainIntensity: {},
    //   bodyPartsForearmPainPattern: {},
    //   bodyPartsForearmPainTiming: {},
    //   bodyPartsForearmSwelling: {},
    //   bodyPartsForearmSwellingWhichArm: {},
    //   bodyPartsForearmSwellingVisibility: {},
    //   bodyPartsForearmSwellingImage: {},
    //   // bodyPartsForearmStiffness: {},
    //   // bodyPartsForearmStiffnessWhichArm: {},
    //   bodyPartsForearmRashBruising: {},
    //   bodyPartsForearmRashBruisingWhichArm: {},
    //   bodyPartsForearmRashBruisingImage: {},
    //   bodyPartsForearmItching: {},
    //   bodyPartsForearmItchingWhichArm: {},
    //   bodyPartsForearmItchingSuddenOnset: {},
    //   bodyPartsForearmItchingDuration: {},
    //   bodyPartsForearmItchingImage: {},
    //   bodyPartsForearmOthers: {},
    // },
    forearm: {
      bodyPartsForearmPain: {
        en: "Forearm Pain",
        bn: "হাতের কনুই থেকে কবজি পর্যন্ত ব্যথা",
        as: "কনইৰ পৰা কবজালৈকে হাতত বিষ",
      },
      bodyPartsForearmPainWhichArm: {
        en: "Which Arm has Pain?",
        bn: "কোন হাতে ব্যথা?",
        as: "কোন বাহুত বিষ আছে?",
      },
      bodyPartsForearmPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsForearmPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsForearmPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsForearmSwelling: {
        en: "Forearm Swelling",
        bn: "হাতের কনুই থেকে কবজি পর্যন্ত ফোলা",
        as: "কনইৰ পৰা কবজালৈকে হাত ফুলা",
      },
      bodyPartsForearmSwellingWhichArm: {
        en: "Which Arm has Swelling?",
        bn: "কোন হাতে ফোলা?",
        as: "কোন বাহুত ফুলা আছে?",
      },
      bodyPartsForearmSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsForearmSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsForearmRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsForearmRashBruisingWhichArm: {
        en: "Which Arm has Rash or Bruising?",
        bn: "কোন হাতে চুলকানি বা রক্তজমাট?",
        as: "কোন বাহুত চুলকনি বা ৰক্ত জমা?",
      },
      bodyPartsForearmRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsForearmItching: {
        en: "Forearm Itching",
        bn: "হাতের কনুই থেকে কবজি পর্যন্ত চুলকানি",
        as: "কনইৰ পৰা কবজালৈকে হাতত চুলকনি",
      },
      bodyPartsForearmItchingWhichArm: {
        en: "Which Arm has Itching?",
        bn: "কোন হাতে চুলকানি?",
        as: "কোন বাহুত চুলকনি?",
      },
      bodyPartsForearmItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsForearmItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsForearmItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsForearmOthers: {
        en: "Other Forearm Symptoms",
        bn: "অন্যান্য আগ বাহুর উপসর্গ",
        as: "অন্যান্য আগ বাহুৰ লক্ষণ",
      },
    },

    // hands: {
    //   bodyPartsHandsPain: {},
    //   bodyPartsHandsPainWhichHand: {},
    //   bodyPartsHandsPainIntensity: {},
    //   bodyPartsHandsPainPattern: {},
    //   bodyPartsHandsPainTiming: {},
    //   bodyPartsHandsSwelling: {},
    //   bodyPartsHandsSwellingWhichHand: {},
    //   bodyPartsHandsSwellingVisibility: {},
    //   bodyPartsHandsSwellingImage: {},
    //   bodyPartsHandsStiffness: {},
    //   bodyPartsHandsStiffnessWhichHand: {},
    //   bodyPartsHandsRashBruising: {},
    //   bodyPartsHandsRashBruisingWhichHand: {},
    //   bodyPartsHandsRashBruisingImage: {},
    //   bodyPartsHandsItching: {},
    //   bodyPartsHandsItchingWhichHand: {},
    //   bodyPartsHandsItchingSuddenOnset: {},
    //   bodyPartsHandsItchingDuration: {},
    //   bodyPartsHandsItchingImage: {},
    //   bodyPartsHandsOthers: {},
    // },
    hands: {
      bodyPartsHandsPain: {
        en: "Hand Pain",
        bn: "হাতে ব্যথা",
        as: "হাতত বিষ",
      },
      bodyPartsHandsPainWhichHand: {
        en: "Which Hand has Pain?",
        bn: "কোন হাতে ব্যথা?",
        as: "কোন হাতত বিষ আছে?",
      },
      bodyPartsHandsPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsHandsPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsHandsPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsHandsSwelling: {
        en: "Hand Swelling",
        bn: "হাতে ফোলা",
        as: "হাতত ফুলা",
      },
      bodyPartsHandsSwellingWhichHand: {
        en: "Which Hand has Swelling?",
        bn: "কোন হাতে ফোলা?",
        as: "কোন হাতত ফুলা আছে?",
      },
      bodyPartsHandsSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsHandsSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsHandsStiffness: {
        en: "Hand Stiffness",
        bn: "হাতে শক্ত হয়ে যাওয়া",
        as: "হাত শক্ত হোৱা",
      },
      bodyPartsHandsStiffnessWhichHand: {
        en: "Which Hand has Stiffness?",
        bn: "কোন হাতে শক্ত হয়েছে?",
        as: "কোন হাত শক্ত হৈছে?",
      },
      bodyPartsHandsRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsHandsRashBruisingWhichHand: {
        en: "Which Hand has Rash or Bruising?",
        bn: "কোন হাতে চুলকানি বা রক্তজমাট?",
        as: "কোন হাতত চুলকনি বা ৰক্ত জমা?",
      },
      bodyPartsHandsRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsHandsItching: {
        en: "Hand Itching",
        bn: "হাতে চুলকানি",
        as: "হাতত চুলকনি",
      },
      bodyPartsHandsItchingWhichHand: {
        en: "Which Hand has Itching?",
        bn: "কোন হাতে চুলকানি?",
        as: "কোন হাতত চুলকনি?",
      },
      bodyPartsHandsItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsHandsItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsHandsItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsHandsOthers: {
        en: "Other Hand Symptoms",
        bn: "অন্যান্য হাতের উপসর্গ",
        as: "অন্যান্য হাতৰ লক্ষণ",
      },
    },

    // fingers: {
    //   bodyPartsFingersPain: {},
    //   // bodyPartsFingersPainWhichFinger: {},
    //   bodyPartsFingersPainIntensity: {},
    //   bodyPartsFingersPainPattern: {},
    //   bodyPartsFingersPainTiming: {},
    //   bodyPartsFingersSwelling: {},
    //   // bodyPartsFingersSwellingWhichFinger: {},
    //   bodyPartsFingersSwellingVisibility: {},
    //   bodyPartsFingersSwellingImage: {},
    //   bodyPartsFingersStiffness: {},
    //   // bodyPartsFingersStiffnessWhichFinger: {},
    //   bodyPartsFingersRashBruising: {},
    //   // bodyPartsFingersRashBruisingWhichFinger: {},
    //   bodyPartsFingersRashBruisingImage: {},
    //   bodyPartsFingersItching: {},
    //   // bodyPartsFingersItchingWhichFinger: {},
    //   bodyPartsFingersItchingSuddenOnset: {},
    //   bodyPartsFingersItchingDuration: {},
    //   bodyPartsFingersItchingImage: {},

    //   bodyPartsFingersNailIssues: {},
    // },
    fingers: {
      bodyPartsFingersPain: {
        en: "Finger Pain",
        bn: "আঙুলে ব্যথা",
        as: "আঙুলিত বিষ",
      },
      bodyPartsFingersPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsFingersPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsFingersPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsFingersSwelling: {
        en: "Finger Swelling",
        bn: "আঙুলে ফোলা",
        as: "আঙুলিত ফুলা",
      },
      bodyPartsFingersSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsFingersSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsFingersStiffness: {
        en: "Finger Stiffness",
        bn: "আঙুলে শক্ত হয়ে যাওয়া",
        as: "আঙুলিত কঠোৰতা",
      },
      bodyPartsFingersRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsFingersRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsFingersItching: {
        en: "Finger Itching",
        bn: "আঙুলে চুলকানি",
        as: "আঙুলিত চুলকনি",
      },
      bodyPartsFingersItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsFingersItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsFingersItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsFingersNailIssues: {
        en: "Nail Issues",
        bn: "নখ সংক্রান্ত সমস্যা",
        as: "নখৰ সমস্যা",
      },
    },
    // chest: {
    //   bodyPartsChestPain: {},
    //   bodyPartsChestPainIntensity: {},
    //   bodyPartsChestPainPattern: {},
    //   bodyPartsChestPainTiming: {},
    //   bodyPartsChestSwelling: {},
    //   bodyPartsChestSwellingVisibility: {},
    //   bodyPartsChestSwellingImage: {},
    //   bodyPartsChestRashBruising: {},
    //   // bodyPartsChestRashBruisingVisibility: {},
    //   bodyPartsChestRashBruisingImage: {},
    //   bodyPartsChestItching: {},
    //   bodyPartsChestItchingSuddenOnset: {},
    //   bodyPartsChestItchingDuration: {},
    //   bodyPartsChestItchingImage: {},
    //   // bodyPartsChestOthers: {},
    // },
    chest: {
      bodyPartsChestPain: {
        en: "Chest Pain",
        bn: "বুকে ব্যথা",
        as: "বক্ষত বিষ",
      },
      bodyPartsChestPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsChestPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsChestPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsChestSwelling: {
        en: "Chest Swelling",
        bn: "বুকে ফোলা",
        as: "বক্ষত ফুলা",
      },
      bodyPartsChestSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsChestSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsChestRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsChestRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsChestItching: {
        en: "Chest Itching",
        bn: "বুকে চুলকানি",
        as: "বক্ষত চুলকনি",
      },
      bodyPartsChestItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsChestItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsChestItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
    },
    // abdomen: {
    //   bodyPartsAbdomenPain: {},
    //   bodyPartsAbdomenPainIntensity: {},
    //   bodyPartsAbdomenPainPattern: {},
    //   bodyPartsAbdomenPainTiming: {},
    //   bodyPartsAbdomenSwelling: {},
    //   bodyPartsAbdomenSwellingVisibility: {},
    //   bodyPartsAbdomenSwellingImage: {},
    //   bodyPartsAbdomenRashBruising: {},
    //   // bodyPartsAbdomenRashBruisingVisibility: {},
    //   bodyPartsAbdomenRashBruisingImage: {},
    //   bodyPartsAbdomenItching: {},
    //   bodyPartsAbdomenItchingSuddenOnset: {},
    //   bodyPartsAbdomenItchingDuration: {},
    //   bodyPartsAbdomenItchingImage: {},
    //   bodyPartsAbdomenOthers: {},
    // },
    abdomen: {
      bodyPartsAbdomenPain: {
        en: "Abdominal Pain",
        bn: "পেটে ব্যথা",
        as: "পেটত বিষ",
      },
      bodyPartsAbdomenPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsAbdomenPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsAbdomenPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsAbdomenSwelling: {
        en: "Abdominal Swelling",
        bn: "পেটে ফোলা",
        as: "পেটত ফুলা",
      },
      bodyPartsAbdomenSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsAbdomenSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsAbdomenRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsAbdomenRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsAbdomenItching: {
        en: "Abdominal Itching",
        bn: "পেটে চুলকানি",
        as: "পেটত চুলকনি",
      },
      bodyPartsAbdomenItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsAbdomenItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsAbdomenItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsAbdomenOthers: {
        en: "Other Abdominal Symptoms",
        bn: "অন্যান্য পেটের উপসর্গ",
        as: "অন্যান্য পেটৰ লক্ষণ",
      },
    },

    // "upper-back": {
    //   bodyPartsUpperBackPain: {},
    //   bodyPartsUpperBackPainIntensity: {},
    //   bodyPartsUpperBackPainPattern: {},
    //   bodyPartsUpperBackPainTiming: {},
    //   bodyPartsUpperBackSwelling: {},
    //   bodyPartsUpperBackSwellingVisibility: {},
    //   bodyPartsUpperBackSwellingImage: {},
    //   bodyPartsUpperBackRashBruising: {},
    //   // bodyPartsUpperBackRashBruisingVisibility: {},
    //   bodyPartsUpperBackRashBruisingImage: {},
    //   bodyPartsUpperBackItching: {},
    //   bodyPartsUpperBackItchingSuddenOnset: {},
    //   bodyPartsUpperBackItchingDuration: {},
    //   bodyPartsUpperBackItchingImage: {},
    //   bodyPartsUpperBackOthers: {},
    // },
    "upper-back": {
      bodyPartsUpperBackPain: {
        en: "Upper Back Pain",
        bn: "পিঠের ওপরের অংশে ব্যথা",
        as: "পিঠৰ ওপৰৰ অংশত বিষ",
      },
      bodyPartsUpperBackPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsUpperBackPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsUpperBackPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsUpperBackSwelling: {
        en: "Upper Back Swelling",
        bn: "পিঠের ওপরের অংশে ফোলা",
        as: "পিঠৰ ওপৰৰ অংশত ফুলা",
      },
      bodyPartsUpperBackSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsUpperBackSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsUpperBackRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsUpperBackRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsUpperBackItching: {
        en: "Upper Back Itching",
        bn: "পিঠের ওপরের অংশে চুলকানি",
        as: "পিঠৰ ওপৰৰ অংশত চুলকনি",
      },
      bodyPartsUpperBackItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsUpperBackItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsUpperBackItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsUpperBackOthers: {
        en: "Other Upper Back Symptoms",
        bn: "অন্যান্য ওপরের পিঠের উপসর্গ",
        as: "অন্যান্য ওপৰ পিঠৰ লক্ষণ",
      },
    },
    // "lower-back": {
    //   bodyPartsLowerBackPain: {},
    //   bodyPartsLowerBackPainIntensity: {},
    //   bodyPartsLowerBackPainPattern: {},
    //   bodyPartsLowerBackPainTiming: {},
    //   bodyPartsLowerBackSwelling: {},
    //   bodyPartsLowerBackSwellingVisibility: {},
    //   bodyPartsLowerBackSwellingImage: {},
    //   bodyPartsLowerBackRashBruising: {},
    //   bodyPartsLowerBackStiffness: {},
    //   // bodyPartsLowerBackRashBruisingVisibility: {},
    //   bodyPartsLowerBackRashBruisingImage: {},
    //   bodyPartsLowerBackItching: {},
    //   bodyPartsLowerBackItchingSuddenOnset: {},
    //   bodyPartsLowerBackItchingDuration: {},
    //   bodyPartsLowerBackItchingImage: {},
    //   bodyPartsLowerBackOthers: {},
    // },
    "lower-back": {
      bodyPartsLowerBackPain: {
        en: "Lower Back Pain",
        bn: "পিঠের নিচের অংশে ব্যথা",
        as: "পিঠৰ তলৰ অংশত বিষ",
      },
      bodyPartsLowerBackPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsLowerBackPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsLowerBackPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsLowerBackSwelling: {
        en: "Lower Back Swelling",
        bn: "পিঠের নিচের অংশে ফোলা",
        as: "পিঠৰ তলৰ অংশত ফুলা",
      },
      bodyPartsLowerBackSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsLowerBackSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsLowerBackRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsLowerBackStiffness: {
        en: "Lower Back Stiffness",
        bn: "পিঠের নিচের অংশে শক্ত হয়ে যাওয়া",
        as: "পিঠৰ তলৰ অংশ শক্ত হোৱা",
      },
      bodyPartsLowerBackRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsLowerBackItching: {
        en: "Lower Back Itching",
        bn: "পিঠের নিচের অংশে চুলকানি",
        as: "পিঠৰ তলৰ অংশত চুলকনি",
      },
      bodyPartsLowerBackItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsLowerBackItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsLowerBackItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsLowerBackOthers: {
        en: "Other Lower Back Symptoms",
        bn: "অন্যান্য নিচের পিঠের উপসর্গ",
        as: "অন্যান্য তলৰ পিঠৰ লক্ষণ",
      },
    },
    // thigh: {
    //   bodyPartsThighPain: {},
    //   bodyPartsThighPainIntensity: {},
    //   bodyPartsThighPainPattern: {},
    //   bodyPartsThighPainTiming: {},
    //   bodyPartsThighSwelling: {},
    //   bodyPartsThighSwellingVisibility: {},
    //   bodyPartsThighSwellingImage: {},
    //   bodyPartsThighRashBruising: {},
    //   // bodyPartsThighRashBruisingVisibility: {},
    //   bodyPartsThighRashBruisingImage: {},
    //   bodyPartsThighItching: {},
    //   bodyPartsThighItchingSuddenOnset: {},
    //   bodyPartsThighItchingDuration: {},
    //   bodyPartsThighItchingImage: {},
    //   bodyPartsThighOthers: {},
    // },
    thigh: {
      bodyPartsThighPain: {
        en: "Thigh Pain",
        bn: "উরুতে ব্যথা",
        as: "উৰুত বিষ",
      },
      bodyPartsThighPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsThighPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsThighPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsThighSwelling: {
        en: "Thigh Swelling",
        bn: "উরুতে ফোলা",
        as: "উৰুত ফুলা",
      },
      bodyPartsThighSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsThighSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsThighRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsThighRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsThighItching: {
        en: "Thigh Itching",
        bn: "উরুতে চুলকানি",
        as: "উৰুত চুলকনি",
      },
      bodyPartsThighItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsThighItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsThighItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsThighOthers: {
        en: "Other Thigh Symptoms",
        bn: "অন্যান্য উরুর উপসর্গ",
        as: "অন্যান্য উৰুৰ লক্ষণ",
      },
    },

    // knee: {
    //   bodyPartsKneePain: {},
    //   bodyPartsKneePainIntensity: {},
    //   bodyPartsKneePainPattern: {},
    //   bodyPartsKneePainTiming: {},
    //   bodyPartsKneeSwelling: {},
    //   bodyPartsKneeSwellingVisibility: {},
    //   bodyPartsKneeSwellingImage: {},
    //   bodyPartsKneeStiffness: {},
    //   bodyPartsKneeRashBruising: {},
    //   // bodyPartsKneeRashBruisingVisibility: {},
    //   bodyPartsKneeRashBruisingImage: {},
    //   bodyPartsKneeItching: {},
    //   bodyPartsKneeItchingSuddenOnset: {},
    //   bodyPartsKneeItchingDuration: {},
    //   bodyPartsKneeItchingImage: {},
    //   // bodyPartsKneeOthers: {},
    // },
    knee: {
      bodyPartsKneePain: {
        en: "Knee Pain",
        bn: "হাঁটুতে ব্যথা",
        as: "ভূঁৰিত বিষ",
      },
      bodyPartsKneePainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsKneePainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsKneePainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsKneeSwelling: {
        en: "Knee Swelling",
        bn: "হাঁটুতে ফোলা",
        as: "ভূঁৰিত ফুলা",
      },
      bodyPartsKneeSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsKneeSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsKneeStiffness: {
        en: "Knee Stiffness",
        bn: "হাঁটু শক্ত হয়ে যাওয়া",
        as: "ভূঁৰি শক্ত হোৱা",
      },
      bodyPartsKneeRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsKneeRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsKneeItching: {
        en: "Knee Itching",
        bn: "হাঁটুতে চুলকানি",
        as: "ভূঁৰিত চুলকনি",
      },
      bodyPartsKneeItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsKneeItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsKneeItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
    },
    // ankle: {
    //   bodyPartsAnklePain: {},
    //   bodyPartsAnklePainIntensity: {},
    //   bodyPartsAnklePainPattern: {},
    //   bodyPartsAnklePainTiming: {},
    //   bodyPartsAnkleSwelling: {},
    //   bodyPartsAnkleSwellingVisibility: {},
    //   bodyPartsAnkleSwellingImage: {},
    //   bodyPartsAnkleStiffness: {},
    //   bodyPartsAnkleRashBruising: {},
    //   // bodyPartsAnkleRashBruisingVisibility: {},
    //   bodyPartsAnkleRashBruisingImage: {},
    //   bodyPartsAnkleItching: {},
    //   bodyPartsAnkleItchingSuddenOnset: {},
    //   bodyPartsAnkleItchingDuration: {},
    //   bodyPartsAnkleItchingImage: {},
    //   // bodyPartsAnkleOthers: {},
    // },
    ankle: {
      bodyPartsAnklePain: {
        en: "Ankle Pain",
        bn: "গাঁটিতে ব্যথা",
        as: "গোঁড়ালিত বিষ",
      },
      bodyPartsAnklePainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsAnklePainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsAnklePainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsAnkleSwelling: {
        en: "Ankle Swelling",
        bn: "গাঁটিতে ফোলা",
        as: "গোঁড়ালিত ফুলা",
      },
      bodyPartsAnkleSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsAnkleSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsAnkleStiffness: {
        en: "Ankle Stiffness",
        bn: "গাঁটি শক্ত হয়ে যাওয়া",
        as: "গোঁড়ালি শক্ত হোৱা",
      },
      bodyPartsAnkleRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsAnkleRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsAnkleItching: {
        en: "Ankle Itching",
        bn: "গাঁটিতে চুলকানি",
        as: "গোঁড়ালিত চুলকনি",
      },
      bodyPartsAnkleItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsAnkleItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsAnkleItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
    },

    // feet: {
    //   bodyPartsFeetPain: {},
    //   bodyPartsFeetPainIntensity: {},
    //   bodyPartsFeetPainPattern: {},
    //   bodyPartsFeetPainTiming: {},
    //   bodyPartsFeetSwelling: {},
    //   bodyPartsFeetSwellingVisibility: {},
    //   bodyPartsFeetSwellingImage: {},
    //   // bodyPartsFeetStiffness: {},
    //   bodyPartsFeetRashBruising: {},
    //   // bodyPartsFeetRashBruisingVisibility: {},
    //   bodyPartsFeetRashBruisingImage: {},
    //   bodyPartsFeetItching: {},
    //   bodyPartsFeetItchingSuddenOnset: {},
    //   bodyPartsFeetItchingDuration: {},
    //   bodyPartsFeetItchingImage: {},
    //   bodyPartsFeetOthers: {},
    // },
    feet: {
      bodyPartsFeetPain: {
        en: "Foot Pain",
        bn: "পায়ে ব্যথা",
        as: "ভৰিত বিষ",
      },
      bodyPartsFeetPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsFeetPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsFeetPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsFeetSwelling: {
        en: "Foot Swelling",
        bn: "পায়ে ফোলা",
        as: "ভৰিত ফুলা",
      },
      bodyPartsFeetSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsFeetSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsFeetRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsFeetRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsFeetItching: {
        en: "Foot Itching",
        bn: "পায়ে চুলকানি",
        as: "ভৰিত চুলকনি",
      },
      bodyPartsFeetItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsFeetItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsFeetItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsFeetOthers: {
        en: "Other Foot Symptoms",
        bn: "অন্যান্য পায়ের উপসর্গ",
        as: "অন্যান্য ভৰিৰ লক্ষণ",
      },
    },
    // toes: {
    //   bodyPartsToesPain: {},
    //   // bodyPartsToesPainWhichToe: {},
    //   bodyPartsToesPainIntensity: {},
    //   bodyPartsToesPainPattern: {},
    //   bodyPartsToesPainTiming: {},
    //   bodyPartsToesSwelling: {},
    //   // bodyPartsToesSwellingWhichToe: {},
    //   bodyPartsToesSwellingVisibility: {},
    //   bodyPartsToesSwellingImage: {},
    //   // bodyPartsToesStiffness: {},
    //   // bodyPartsToesStiffnessWhichToe: {},
    //   bodyPartsToesRashBruising: {},
    //   // bodyPartsToesRashBruisingWhichToe: {},
    //   bodyPartsToesRashBruisingImage: {},
    //   bodyPartsToesItching: {},
    //   // bodyPartsToesItchingWhichToe: {},
    //   bodyPartsToesItchingSuddenOnset: {},
    //   bodyPartsToesItchingDuration: {},
    //   bodyPartsToesItchingImage: {},
    //   bodyPartsToesOthers: {},
    // },
    toes: {
      bodyPartsToesPain: {
        en: "Toe Pain",
        bn: "আঙুলিতে ব্যথা",
        as: "ভৰিৰ আঙুলিত বিষ",
      },
      bodyPartsToesPainIntensity: {
        en: "Pain Intensity",
        bn: "ব্যথার তীব্রতা",
        as: "বিষৰ তীব্ৰতা",
      },
      bodyPartsToesPainPattern: {
        en: "Pain Pattern",
        bn: "ব্যথার ধরণ",
        as: "বিষৰ ধৰণ",
      },
      bodyPartsToesPainTiming: {
        en: "Pain Timing",
        bn: "ব্যথার সময়কাল",
        as: "বিষৰ সময়",
      },
      bodyPartsToesSwelling: {
        en: "Toe Swelling",
        bn: "আঙুলিতে ফোলা",
        as: "ভৰিৰ আঙুলিত ফুলা",
      },
      bodyPartsToesSwellingVisibility: {
        en: "Swelling Visibility",
        bn: "ফোলার দৃশ্যমানতা",
        as: "ফুলাৰ দৃশ্যতা",
      },
      bodyPartsToesSwellingImage: {
        en: "Swelling Image",
        bn: "ফোলার ছবি",
        as: "ফুলাৰ ছবি",
      },
      bodyPartsToesRashBruising: {
        en: "Rash or Bruising",
        bn: "চুলকানি বা রক্তজমাট",
        as: "চুলকনি বা ৰক্ত জমা",
      },
      bodyPartsToesRashBruisingImage: {
        en: "Rash/Bruising Image",
        bn: "চুলকানি/রক্তজমাট ছবি",
        as: "চুলকনি/ৰক্ত জমাৰ ছবি",
      },
      bodyPartsToesItching: {
        en: "Toe Itching",
        bn: "আঙুলিতে চুলকানি",
        as: "ভৰিৰ আঙুলিত চুলকনি",
      },
      bodyPartsToesItchingSuddenOnset: {
        en: "Sudden Onset of Itching",
        bn: "হঠাৎ চুলকানি শুরু",
        as: "হঠাতে চুলকনি আৰম্ভ হোৱা",
      },
      bodyPartsToesItchingDuration: {
        en: "Itching Duration",
        bn: "চুলকানির সময়কাল",
        as: "চুলকনিৰ সময়কাল",
      },
      bodyPartsToesItchingImage: {
        en: "Itching Image",
        bn: "চুলকানির ছবি",
        as: "চুলকনিৰ ছবি",
      },
      bodyPartsToesOthers: {
        en: "Other Toe Symptoms",
        bn: "অন্যান্য আঙুলির উপসর্গ",
        as: "অন্যান্য ভৰিৰ আঙুলিৰ লক্ষণ",
      },
    },
  },
  others: {
    others: {
      fatigue: {
        en: "Fatigue",
        bn: "শক্তিহীনতা",
        as: "শক্তিহীনতা",
      },
      anxiety: {
        en: "Anxiety",
        bn: "উদ্বেগ",
        as: "উদ্বেগ",
      },
      difficultyConcentration: {
        en: "Difficulty Concentrating",
        bn: "কেন্দ্রীভূত করতে অসুবিধা",
        as: "কেন্দ্ৰিত কৰাত অসুবিধা",
      },
      stress: {
        en: "Mental Stress",
        bn: "মানসিক চাপ",
        as: "মানসিক চাপ",
      },
      sleepDisturbance: {
        en: "Sleep Disturbance",
        bn: "ঘুমের ব্যাঘাত",
        as: "ঘুমৰ ব্যাঘাত",
      },
      lossOfAppetite: {
        en: "Loss of Appetite",
        bn: "রুচি হ্রাস",
        as: "ৰুচি হ্ৰাস",
      },
      weight: {
        en: "Weight Changes",
        bn: "ওজন পরিবর্তন",
        as: "ওজনৰ পৰিবৰ্তন",
      },
      acidReflux: {
        en: "Acid Reflux",
        bn: "অ্যাসিড রিফ্লাক্স",
        as: "অ্যাসিড ৰিফ্লাক্স",
      },
      others: {
        en: "Others",
        bn: "অন্যান্য",
        as: "অন্যান্য",
      },
    },
  },
};
